#!/bin/bash

apt-get update
apt-get install vim -y
apt-get install calcurse -y
apt-get install net-tools -y
mkdir $HOME/.calcurse
cp ./conf $HOME/.calcurse/conf
apt-get install tmux -y
apt-get install w3m -y
apt-get install mutt -y
apt-get install iputils-ping -y
apt-get install curl -y

cp ./.tmux.conf ~/

# set central timezone
rm /etc/localtime
ln -s /usr/share/zoneinfo/US/Central /etc/localtime

