#!/bin/bash

sudo apt-get update
sudo apt-get install vim net-tools iputils-ping curl -y

#Set timezone to Central (or whatever)
sudo rm /etc/localtime
sudo ln -s /usr/share/zoneinfo/US/Central /etc/localtime

#Simplify Command Prompt
PS1="\w/ $ "

#VIM Configuration
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s ~/git/drive/config-link/.vimrc ~/.vimrc


#GIT
sudo git config --global user.email "slingmint@gmail.com"
git config --global user.email "slingmint@gmail.com"


#i3

sudo apt-get install i3 -y

git clone https://github.com/tobi-wan-kenobi/bumblebee-status ~/git/bumblebee-status

sudo apt-get install fonts-font-awesome -y

sudo apt-get install fonts-powerline -y


mkdir ~/.config/i3
mv ~/.config/i3/config ~/.config/i3/config-old
#note if the above two fail, that's ok ... they handle install and uninstall together (one will always fail)
ln ~/git/drive/i3/config ~/.config/i3/config


#GNOME-TERMINAL
echo "[:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
backgroud-color='rgb(0,0,0)'
font='DejaVu Sans Mono 18'
foreground-color='rgb(0,255,0)'
use-system-font=false
use-theme-colors=false" > ~/gnome-terminal-temp

dconf load /org/gnome/terminal/legacy/profiles:/ < ~/gnome-terminal-temp

rm ~/gnome-terminal-temp





